# python3 main.py --data_path /home/infres/amathur-23/DADA/datasets/InTheWild --model_save_path /home/infres/amathur-23/DADA/src/models --dataset_config configs/data/inthewild_10v8.yaml --loss_fn squared_similarity --gpu_id 1 --epochs=10 --log_dir=runs/sq_sim_10v8 --batch_size=16 --at_lambda=0 --margin=0.5 --lr_scheduler cosine --early_stopping_metric=accuracy

# python3 main.py --data_path /home/infres/amathur-23/DADA/datasets/InTheWild --model_save_path /home/infres/amathur-23/DADA/src/models --dataset_config configs/data/inthewild_10v8.yaml --loss_fn ada_triplet --gpu_id 1 --epochs=10 --log_dir=runs/tricos_p5_PLUS_ada2 --batch_size=16 --at_lambda=0 --margin=0.5 --lr_scheduler cosine --early_stopping_metric=accuracy --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/tri_cosine_10v8_eps_p5'

# python3 main.py --data_path /home/infres/amathur-23/DADA/datasets/InTheWild --model_save_path /home/infres/amathur-23/DADA/src/models --dataset_config configs/data/inthewild_10v8.yaml --loss_fn triplet_cosine --gpu_id 1 --epochs=10 --log_dir=runs/tricos_p35_10v8 --batch_size=16 --at_lambda=0 --margin=0.35 --lr_scheduler cosine --early_stopping_metric=accuracy 

# python3 main.py --data_path /home/infres/amathur-23/DADA/datasets/InTheWild --model_save_path /home/infres/amathur-23/DADA/src/models --dataset_config configs/data/inthewild_all.yaml --loss_fn triplet_cosine --gpu_id 2 --epochs=1 --log_dir=runs/jlt --batch_size=16 --at_lambda=0 --margin=0.35 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True

# python3 main.py --dataset voxceleb2 --data_path /data/amathur-23/DADA/VoxCeleb2 --model_save_path /data/amathur-23/DADA/models --dataset_config configs/data/inthewild_all.yaml --loss_fn triplet_cosine --gpu_id 2 --epochs=1 --log_dir=runs/voxceleb_run1 --batch_size=16 --at_lambda=0 --margin=0.35 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True


# python3 main.py --dataset commonvoice --data_path /data/amathur-23/DADA/CommonVoice --model_save_path /data/amathur-23/DADA/models --dataset_config configs/data/inthewild_all.yaml --loss_fn ada_triplet --gpu_id 2 --epochs=10 --log_dir=runs/commonvoice_run_ada --batch_size=16 --at_lambda=0 --margin=0.35 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/commonvoice_run1'

# python3 main.py --dataset ravdess --data_path /data/amathur-23/DADA/RAVDESS --model_save_path /data/amathur-23/DADA/models --dataset_config "/data/amathur-23/DADA/RAVDESS/ravdess_config.yaml" --loss_fn triplet_cosine --gpu_id 2 --epochs=30 --log_dir=runs/commonvoice_plus_ravdess --batch_size=16 --at_lambda=0 --margin=0.4 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/commonvoice_run_ada'

# python3 main.py --datasets commonvoice ravdess --data_path /data/amathur-23/DADA --model_save_path /data/amathur-23/DADA/models --dataset_config "/data/amathur-23/DADA/RAVDESS/ravdess_config.yaml" --loss_fn triplet_cosine --gpu_id 2 --epochs=30 --log_dir=runs/commonvoice_plus_ravdess_combined_p4 --batch_size=16 --at_lambda=0 --margin=0.4 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/commonvoice_plus_ravdess'

# python3 main.py --datasets voxceleb2 --data_path /data/amathur-23/DADA --model_save_path /data/amathur-23/DADA/models --dataset_config "/data/amathur-23/DADA/RAVDESS/ravdess_config.yaml" --loss_fn triplet_cosine --gpu_id 2 --epochs=50 --log_dir=runs/commonvoice_ravdess_voxceleb2_combined_p4 --batch_size=16 --at_lambda=0 --margin=0.4 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/commonvoice_plus_ravdess_combined_p4_ada' --early_stopping_patience=5


python3 main.py --datasets voxceleb2 --data_path /data/amathur-23/DADA --model_save_path /data/amathur-23/DADA/models --dataset_config "/data/amathur-23/DADA/RAVDESS/ravdess_config.yaml" --loss_fn ada_triplet --gpu_id 2 --epochs=5 --log_dir=runs/voxceleb_tune_ada --batch_size=16 --at_lambda=0 --margin=0.4 --lr_scheduler plateau --early_stopping_metric=accuracy --save_visualisations=True --load_path='/data/amathur-23/DADA/models/SpeechEmbedder/commonvoice_ravdess_voxceleb2_combined_p4' --early_stopping_patience=3